line-length = 100

[lint]
select = ["ALL"]
ignore = [
  # "C408",  # "Unnecessary" `dict`, `list` or `tuple` calls instead of literals
  "Q",  # Quotes
  "ANN101",  # Annotate self
  "ANN102",  # Annotate cls
  "SLF001",  # Access private _member
  "RET505",  # Else after return
  "ARG002",  # Unused method argument
  "PLW0603",  # Global statement to update variable
  "PLR0913",  # Too many arguments
  "S101",  # Use of `assert` detected
  "RET504",  # Unnecessary assignment to `...` before `return` statement
  "A001",  # Variable `...` is shadowing a Python builtin
  "A002",  # Function argument `...` is shadowing a Python builtin
  "PLR2004",  # Magic value used in comparison

  "D",  # Temporarily: docstrings
  "ERA001",  # Temporarily: commented out code
]

[lint.per-file-ignores]
"tests/*" = [
  "D",  # Docstrings
  "S101",  # Use of assert
]

[lint.flake8-comprehensions]
allow-dict-calls-with-keyword-arguments = true

[lint.pydocstyle]
convention = "google"

[lint.mccabe]
max-complexity = 15

[lint.flake8-annotations]
allow-star-arg-any = true

[flake8-builtins]
builtins-ignorelist = ["help"]

[format]
quote-style = "single"
skip-magic-trailing-comma = false
